Update changelog with note about hipGraphs
ROCmSoftwarePlatform/hipCUB pull request #354
Opened 2024-04-03 15:16 UTC by umfranzw

The GridBarrierLifetime and CachingDeviceAllocator classes both issue synchronous calls to hipMalloc and hipFree.

This change modifies GridBarrierLifetime slightly so that it issues asynchronous calls instead. This allows the barrier to be used inside of hipGraphs. The GridBarrier unit test has also been updated to exercise the new changes inside of hipGraphs.

CachingDeviceAllocator is intended to be used together with multiple streams. It operates a bit like a memory pool that works across streams. For example, suppose a memory block is allocated in one stream. When it's freed, no call to hipFree actually occurs - instead, it is marked as "cached." If another stream later allocates a block of similar size, the cached memory block can be re-used (saving a call to hipMalloc).

While eliminating synchronous class from this class is technically possible, it is not very practical. hipGraphs created using stream-capture will capture calls issued into a single stream. Capturing an instance of (a fully asynchronous) CachingDeviceAllocator inside a graph could result in unexpected behaviour if it allocated or freed memory in streams other than the one being captured.

For this reason, I haven't modified CachingDeviceAllocator, and it retains its synchronous calls. I've added a note to the changelog about this, so that users are aware that it won't work within hipGraphs.

2024-04-04 20:08 UTC, umfranzw commented
I've rebased this to resolve the conflicts.

2024-04-05 11:46 UTC, Naraenda requested changes
I'm getting the following build error while compiling tests for NVCC
```
../test/hipcub/test_hipcub_grid.cpp(96): error: no instance of constructor "hipcub::GridBarrierLifetime::GridBarrierLifetime" matches the argument list
            argument types are: (hipStream_t)
      hipcub::GridBarrierLifetime global_barrier(stream);
                                                 ^
1 error detected in the compilation of "../test/hipcub/test_hipcub_grid.cpp".
```

The constructor in `hipcub/include/hipcub/backend/cub/grid/grid_barrier.hpp` also needs to be changed.

2024-04-05 13:19 UTC, nolmoonen requested changes
The change to `GridBarrierLifetime` breaks compatibility with CUB, which goes against the purpose of the library.

AFAICT (but I may be mistaken in this) `hip/cudaMallocAsync(void**, size_t, cudaStream_t(0))` is not the same as `hip/cudaMalloc(void**, size_t)` since the latter is synchronous with the device, the former is not. The same goes for the free variants. This can cause unexpected differences between CUB and hipCUB.

Furthermore, if CUB decides to change the interface of `GridBarrierLifetime`, hipCUB may not be to make the same change without making a breaking change to the hipCUB interface.

I think the proper solution is to add `GridBarrierLifetime` to one of the exceptions of `hipGraph`.

2024-04-08 13:28 UTC, umfranzw commented
@nolmoonen Thanks for the feedback - that makes sense. I was a little uncertain about how much flexibility we had to add default-valued parameters because of the need to maintain compatibility with CUB. I'll update the PR to remove the changes to GridBarrierLifetime and add another note to the changelog to let users know it won't work inside of hipGraphs. I believe that means we don't actually need any changes to hipCUB itself to support hipGraphs, which is nice.

Just as a side-note, the behaviour I've been observing as I've been testing this hipGraph stuff is that a hip/cudaMallocAsync call issued to stream 0 does still block like hip/cudaMalloc does. I also noticed that the CUDA documentation mentions this behaviour [here](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#default-stream).

2024-04-08 13:30 UTC, umfranzw commented
@Naraenda Thanks for catching that - I'd neglected to update the CUB backend code. As per @nolmoonen's  suggestion, I'll remove the GridLifetimeBarrier changes and add a note to the changelog.

2024-04-09 07:36 UTC, Naraenda approved these changes
Thanks, LGTM!

2024-04-09 11:35 UTC, nolmoonen approved these changes

2024-04-09 12:36 UTC, merged